name: Comment on PR when pushed

on:
  push:
    branches:
      - '**'   # runs for all branches

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Find related PR for this branch/commit
        id: find_pr
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            // Get open PRs and try to match by commit first, then by branch name
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });

            let pr = prs.find(p => p.head.sha === context.sha);
            if (!pr) {
              pr = prs.find(p => p.head.ref === branch);
            }

            core.setOutput('pr_number', pr ? pr.number.toString() : '');
      - name: Comment on PR
        if: steps.find_pr.outputs.pr_number != ''
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt('${{ steps.find_pr.outputs.pr_number }}', 10),
              body: `📦 New push detected on \`${context.ref.replace('refs/heads/','')}\` at \`${context.sha.slice(0,7)}\`.`
            });
