name: Comment on PR when pushed

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run comment script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_API_URL: ${{ github.api_url }}
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}  # <- enables commit list
        run: |
          python .github/scripts/comment_on_push.py
